# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib savvyAltrepTest, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

#' Convert Input To Upper-Case
#'
#' @param x A character vector.
#' @returns A character vector with upper case version of the input.
#' @export
to_upper <- function(x) {
  .Call(savvy_to_upper__impl, x)
}

#' Multiply Input By Another Input
#'
#' @param x An integer vector.
#' @param y An integer to multiply.
#' @returns An integer vector with values multiplied by `y`.
#' @export
int_times_int <- function(x, y) {
  .Call(savvy_int_times_int__impl, x, y)
}

### wrapper functions for Person

Person_set_name <- function(self) {
  function(name) {
  invisible(.Call(savvy_Person_set_name__impl, self, name))
  }
}

Person_name <- function(self) {
  function() {
  .Call(savvy_Person_name__impl, self)
  }
}

.savvy_wrap_Person <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
    e$set_name <- Person_set_name(ptr)
  e$name <- Person_name(ptr)
  
  class(e) <- "Person"
  e
}



Person <- new.env(parent = emptyenv())

### associated functions for Person

Person$new <- function() {
  .savvy_wrap_Person(.Call(savvy_Person_new__impl))
}

Person$associated_function <- function() {
.Call(savvy_Person_associated_function__impl)
}


